# Generated by Django 4.0.2 on 2023-10-05 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_branch_customer_branch_customerexpence_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk_storage', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('expense', models.DecimalField(decimal_places=2, max_digits=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='customerexpence',
            name='expence_amount',
        ),
        migrations.RemoveField(
            model_name='customerexpence',
            name='expence_type',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='expence',
            name='expence_name',
        ),
        migrations.AddField(
            model_name='branch',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('customer', 'Customer')], default='customer', max_length=10),
        ),
        migrations.AddField(
            model_name='customerexpence',
            name='expense_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customerexpence',
            name='expense_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expence',
            name='expense_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerexpence',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.branch'),
        ),
        migrations.AlterField(
            model_name='expence',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.branch'),
        ),
        migrations.AlterField(
            model_name='makepayment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.branch'),
        ),
        migrations.AlterField(
            model_name='milkpurchase',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.branch'),
        ),
        migrations.AlterField(
            model_name='milksale',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.branch'),
        ),
        migrations.AlterField(
            model_name='receivedpayment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.branch'),
        ),
        migrations.DeleteModel(
            name='Stor',
        ),
        migrations.AddField(
            model_name='storage',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.branch'),
        ),
    ]
