# Generated by Django 4.0.2 on 2023-10-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0011_customer_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='closing_balance',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='milkcenter',
            name='closing_balance',
            field=models.DecimalField(decimal_places=2, default=0.0037953795379537954, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='milkcenter',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
