# Generated by Django 4.0.2 on 2023-10-08 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0014_makepayment_balance_receivedpayment_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='user',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='user_type',
        ),
        migrations.AddField(
            model_name='customuser',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='Store.branch'),
        ),
    ]
