# Generated by Django 4.0.2 on 2023-10-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0017_alter_milkpurchase_fat_alter_milkpurchase_lr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milksale',
            name='Fat',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='milksale',
            name='LR',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='milksale',
            name='SNF',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='milksale',
            name='price_on_TS',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
